language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit

after_script:
  - composer require phpunit/phpcov=*'
  - wget https://scrutinizer-ci.com/ocular.phar'
  - php ocular.phar code-coverage:upload --format=php-clover ./clover/phpunit.xml'
  - php ocular.phar code-coverage:upload --format=php-clover ./clover/phpspec.xml'
